### ISSUE TITLE
margin to working in container

### ISSUE THREAD

**Issue by swaraj344** [lalitjarwal/hovering#1]
HoverContainer(
            // hoverMargin: EdgeInsets.all(10),
            padding: EdgeInsets.symmetric(horizontal: 20, vertical: 8),
            margin: EdgeInsets.all(10),
            decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(20),
                boxShadow: [
                  BoxShadow(
                      color: Colors.grey.withOpacity(0.5),
                      spreadRadius: 2,
                      blurRadius: 7,
                      offset: Offset(0, 2))
                ]),
            child: Text(
              "PARTNER WITH US",
              style: TextStyle(color: Color(0xff90EA4A)),
            ),
          )
![Annotation 2020-11-14 091031](https://user-images.githubusercontent.com/52861510/99138791-4d8d9000-2659-11eb-806b-551d385d5e33.jpg)

**Comment by swaraj344** [comment]
you just forget to add margin property to the container

**Comment by lalitjarwal** [comment]
Thanks for reminding me.
