### ISSUE TITLE
Package floods standard output with meaningless print outs.

### ISSUE THREAD

**Issue by valckmir** [lalitjarwal/hovering#6]
Each time a hovering widget is hovered, the some time-ish log is printed to standard outputs. This floods the output making the important messages disappearing.

Steps to reproduce:
create `HoverContainer` and hover it

![image](https://user-images.githubusercontent.com/18383340/111133747-25685c00-857b-11eb-8866-3a4d8e40cfb7.png)

**Comment by lalitjarwal** [comment]
Solved.
Thanks for reporting.
