### ISSUE TITLE
Weird Moving/Alignment Issues when Hovering

### ISSUE THREAD

**Issue by ghost** [lalitjarwal/hovering#7]
Seems like a very cool and powerful package, however I'm getting the following weird activity when I put a hoverbutton in a row. What's odd is that some "move" and some don't. And if I change the length of the text that also affects whether it "moves" or not.

Am I doing something wrong or is this just a bug in the code?

https://user-images.githubusercontent.com/47377413/115136203-53aee080-9fec-11eb-9ab8-3159006907ab.mov

**Comment by Nandan-Wewhare** [comment]
Please share the code too it'll be a bit more helpful.

**Comment by ghost** [comment]
@override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: <Widget>[
        HoverButton(
          onpressed: () => null,
          hoverColor: Colors.white,
          textColor: Colors.black,
          hoverTextColor: Colors.blueAccent,
          enableFeedback: false,
          hoverShape: const StadiumBorder(),
          child: Text(
            'test4444444',
            style: const TextStyle(fontSize: 18),
          ),
        ), //const SizedBox(width: 60),
        HoverButton(
          onpressed: () => null,
          hoverColor: Colors.white,
          textColor: Colors.black,
          hoverTextColor: Colors.blueAccent,
          enableFeedback: false,
          hoverShape: const StadiumBorder(),
          child: Text(
            'test4',
            style: const TextStyle(fontSize: 18),
          ),
        ),
        //const SizedBox(width: 60),
        HoverButton(
          onpressed: () => null,
          hoverColor: Colors.white,
          textColor: Colors.black,
          hoverTextColor: Colors.blueAccent,
          enableFeedback: false,
          hoverShape: const StadiumBorder(),
          child: Text(
            'test44',
            style: const TextStyle(fontSize: 18),
          ),
        ),
        //const SizedBox(width: 60),
        HoverButton(
          onpressed: () => null,
          hoverColor: Colors.white,
          textColor: Colors.black,
          hoverTextColor: Colors.blueAccent,
          enableFeedback: false,
          hoverShape: const StadiumBorder(),
          child: Text(
            'test4444',
            style: const TextStyle(fontSize: 18),
          ),
        ),
      ],
    );
  }

**Comment by lalitjarwal** [comment]
add minWidth according to the child.
or 
apply hoverPadding accordingly
ex:

HoverButton(
                onpressed: () => null,
                hoverColor: Colors.white,
                textColor: Colors.black,
                hoverTextColor: Colors.blueAccent,
                enableFeedback: false,
                hoverShape: const StadiumBorder(),
                //hoverPadding: EdgeInsets.symmetric(horizontal: 16.0),
                minWidth: 200, // change it according to length of child
                child: Text(
                  'test444444',
                  style: const TextStyle(fontSize: 18),
                ),
              )
